package com.expensemanager.service;

import com.expensemanager.entity.Expense;
import com.expensemanager.entity.User;
import com.expensemanager.repository.ExpenseRepository;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;

@Service
@RequiredArgsConstructor
public class ReportService {

    private final ExpenseRepository expenseRepository;

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 20, Font.BOLD, new Color(79, 70, 229));
    private static final Font SUBTITLE_FONT = new Font(Font.HELVETICA, 11, Font.NORMAL, new Color(100, 116, 139));
    private static final Font HEADER_FONT = new Font(Font.HELVETICA, 10, Font.BOLD, Color.WHITE);
    private static final Font CELL_FONT = new Font(Font.HELVETICA, 9, Font.NORMAL, new Color(30, 41, 59));
    private static final Font SECTION_FONT = new Font(Font.HELVETICA, 13, Font.BOLD, new Color(30, 41, 59));
    private static final Color BRAND = new Color(79, 70, 229);

    public byte[] generateMonthlyPdf(User user, Integer month, Integer year) {
        YearMonth ym = YearMonth.of(year, month);
        LocalDate start = ym.atDay(1);
        LocalDate end = ym.atEndOfMonth();

        List<Expense> expenses = expenseRepository
                .findByUserIdAndExpenseDateBetweenOrderByExpenseDateDesc(user.getId(), start, end);
        expenses.sort(Comparator.comparing(Expense::getExpenseDate));

        double total = expenses.stream().mapToDouble(Expense::getAmount).sum();

        try {
            Document document = new Document(PageSize.A4, 40, 40, 50, 50);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            PdfWriter.getInstance(document, out);
            document.open();

            document.add(new Paragraph("ExpenseIQ", TITLE_FONT));
            document.add(new Paragraph(
                    "Monthly Expense Report \u2014 " + ym.format(DateTimeFormatter.ofPattern("MMMM yyyy")),
                    SUBTITLE_FONT));
            document.add(new Paragraph("Generated for: " + user.getFullName() + " (" + user.getEmail() + ")",
                    SUBTITLE_FONT));
            document.add(Chunk.NEWLINE);

            // Summary box
            PdfPTable summary = new PdfPTable(3);
            summary.setWidthPercentage(100);
            addSummaryCell(summary, "Total Spent", String.format("Rs. %,.2f", total));
            addSummaryCell(summary, "Transactions", String.valueOf(expenses.size()));
            addSummaryCell(summary, "Monthly Income",
                    String.format("Rs. %,.2f", user.getMonthlyIncome() == null ? 0 : user.getMonthlyIncome()));
            document.add(summary);
            document.add(Chunk.NEWLINE);

            document.add(new Paragraph("Transaction Details", SECTION_FONT));
            document.add(Chunk.NEWLINE);

            PdfPTable table = new PdfPTable(new float[] { 2f, 2.5f, 2f, 1.8f, 1.7f });
            table.setWidthPercentage(100);
            addHeaderCell(table, "Date");
            addHeaderCell(table, "Title");
            addHeaderCell(table, "Category");
            addHeaderCell(table, "Payment");
            addHeaderCell(table, "Amount");

            boolean alt = false;
            for (Expense e : expenses) {
                Color bg = alt ? new Color(248, 250, 252) : Color.WHITE;
                addBodyCell(table, e.getExpenseDate().toString(), bg);
                addBodyCell(table, e.getTitle() == null || e.getTitle().isBlank() ? "-" : e.getTitle(), bg);
                addBodyCell(table, e.getCategory().getName(), bg);
                addBodyCell(table, e.getPaymentMode().toString(), bg);
                addBodyCell(table, String.format("Rs. %,.2f", e.getAmount()), bg);
                alt = !alt;
            }
            if (expenses.isEmpty()) {
                PdfPCell empty = new PdfPCell(new Phrase("No expenses recorded for this month.", CELL_FONT));
                empty.setColspan(5);
                empty.setPadding(10);
                table.addCell(empty);
            }
            document.add(table);

            document.add(Chunk.NEWLINE);
            Paragraph footer = new Paragraph("Generated by ExpenseIQ \u2014 Smart Expense Management System",
                    SUBTITLE_FONT);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            return out.toByteArray();
        } catch (DocumentException ex) {
            throw new RuntimeException("Failed to generate PDF report", ex);
        }
    }

    public byte[] generateMonthlyCsv(User user, Integer month, Integer year) {
        YearMonth ym = YearMonth.of(year, month);
        LocalDate start = ym.atDay(1);
        LocalDate end = ym.atEndOfMonth();

        List<Expense> expenses = expenseRepository
                .findByUserIdAndExpenseDateBetweenOrderByExpenseDateDesc(user.getId(), start, end);

        StringBuilder sb = new StringBuilder();
        sb.append("Date,Title,Category,Payment Mode,Amount,Notes\n");
        for (Expense e : expenses) {
            sb.append(csv(e.getExpenseDate().toString())).append(',')
                    .append(csv(e.getTitle())).append(',')
                    .append(csv(e.getCategory().getName())).append(',')
                    .append(csv(e.getPaymentMode().toString())).append(',')
                    .append(e.getAmount()).append(',')
                    .append(csv(e.getDescription()))
                    .append('\n');
        }
        return sb.toString().getBytes();
    }

    private String csv(String value) {
        if (value == null)
            return "";
        String escaped = value.replace("\"", "\"\"");
        return "\"" + escaped + "\"";
    }

    private void addSummaryCell(PdfPTable table, String label, String value) {
        PdfPCell cell = new PdfPCell();
        cell.setPadding(10);
        cell.setBackgroundColor(new Color(238, 242, 255));
        cell.setBorderColor(new Color(224, 231, 255));
        Paragraph p = new Paragraph();
        p.add(new Chunk(label + "\n", new Font(Font.HELVETICA, 9, Font.NORMAL, new Color(100, 116, 139))));
        p.add(new Chunk(value, new Font(Font.HELVETICA, 13, Font.BOLD, BRAND)));
        cell.addElement(p);
        table.addCell(cell);
    }

    private void addHeaderCell(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, HEADER_FONT));
        cell.setBackgroundColor(BRAND);
        cell.setPadding(6);
        table.addCell(cell);
    }

    private void addBodyCell(PdfPTable table, String text, Color bg) {
        PdfPCell cell = new PdfPCell(new Phrase(text, CELL_FONT));
        cell.setBackgroundColor(bg);
        cell.setPadding(6);
        table.addCell(cell);
    }
}
