spring.application.name=expense-management-system

# ---------------- PostgreSQL Database ----------------
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_management_db
spring.datasource.username=postgres
spring.datasource.password=postgre123
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------- JPA / Hibernate ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ---------------- Server ----------------
server.port=8080
server.error.include-message=always

# ---------------- JWT ----------------
app.jwt.secret=ExpenseManagementSystemSuperSecretKeyForJwtTokenGeneration2024ChangeInProd
app.jwt.expiration-ms=86400000

# ---------------- CORS ----------------
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# ---------------- Logging ----------------
logging.level.com.expensemanager=INFO
